### ISSUE TITLE
Tupperbox webhook not changing name from Tupperhook

### ISSUE THREAD

**Issue by natee22** [Keterr/Tupperbox#106]
![image](https://user-images.githubusercontent.com/5056538/96047037-75af8680-0e42-11eb-98b6-53dea02b374a.png)

**Comment by Keterr** [comment]
This is a Discord problem and not anything we can do anything about. Discord has been made aware of the issue and it is also affecting all similar bots like PluralKit. Please join the support server for updates: https://discord.gg/rHxMbt2

**Comment by Sukasa** [comment]
Could this be pinned & open?  Having to delve into closed issues to find a current issue, even if it's not possible for you all to actually address, makes it hard to know whats going on

**Comment by Keterr** [comment]
@Sukasa Good point, I was just wanting people to go to the support server instead of using gh issues but having it open will increase visibility both ways

**Comment by Keterr** [comment]
The current status of this issue is that a temporary fix has been deployed to the live bot (https://github.com/Keterr/eris/commit/abd46435d3b4a51f1781b7836f43efe819f22b5a) and may be pulled into selfhosted forks for the time being until Discord changes this parameter back on their end. I will make another commit on the fork and close this issue when that time comes.

**Comment by Keterr** [comment]
This issue is now resolved. Discord's incident log here: https://discordstatus.com/incidents/yh6z8rjm4xvm
