### ISSUE TITLE
Tupperbox recently stopped using external emojis

### ISSUE THREAD

**Issue by immortalzero** [Keterr/Tupperbox#118]
Up until around the 13th of this month, Tupperbox had been able to use external emojis in servers where external emojis were enabled so long as users had nitro. This is no longer the case it seems and I was wondering if this was a bug. Please fix it! I really enjoy using external emojis for goofy moments in roleplay. Tupperbox can still use animated emojis in servers if you have nitro so I don’t believe this was on purpose.

**Comment by greysdawn** [comment]
This isn't a bug on Tupper's side, it's a permissions issue in your server(s). Make sure your server's @/everyone role has the ability to use external emoji in the channels you want to use external emoji in. There's also an FAQ entry in the support server for this if you're in there

**Comment by AlexanderOReilly** [comment]
> 
> 
> This isn't a bug on Tupper's side, it's a permissions issue in your server(s). Make sure your server's @/everyone role has the ability to use external emoji in the channels you want to use external emoji in. There's also an FAQ entry in the support server for this if you're in there

It's not an isolated incident though. Every server I'm in has external emoji's enabled. I can use the external emoji's but Tupperbox cannot, but before the 13th of February, Tupperbox was also able to use external emoji's in any server where it was enabled. I've tested this in my own private server and in multiple other servers. For example; 
![image](https://user-images.githubusercontent.com/79121813/108584589-89817100-737d-11eb-9457-84bf33cd01d9.png)

**Comment by greysdawn** [comment]
Can you take a screenshot of BOTH the permissions for the general @/everyone role *and* its permissions in those channels? They should look like this:

![role permissions](https://user-images.githubusercontent.com/29555267/108585217-3c69b480-7315-11eb-8cd3-dfa8921922df.jpg)

![channel permissions](https://user-images.githubusercontent.com/29555267/108585220-44295900-7315-11eb-8136-d673a81f1298.jpg)

**Comment by AlexanderOReilly** [comment]
Sure.
Tupperbox has it.
![image](https://user-images.githubusercontent.com/79121813/108585284-918fdf80-7382-11eb-9911-5c09ec3e6b9d.png)
@/everyone in roles has it.
![image](https://user-images.githubusercontent.com/79121813/108585288-9b194780-7382-11eb-8ad6-e1ad6366d5dd.png)
Ah, I see the issue now. It seemed to be the permissions for @/everyone in the channel specifically that caused it. But that's odd, because it still wasn't working in another server I'm in.
I suppose that's problem solved, though! That might just be them, and I'll make sure they've got it all enabled in case. Thanks a lot!

**Comment by greysdawn** [comment]
Glad to help :)
