### ISSUE TITLE
You know exactly why it died.

### ISSUE THREAD

**Issue by Broski21** [Keterr/Tupperbox#90]
"Also i see a lot of chatter over alleged abuse of the bot causing this crash - the only thing I will note is that those users were already blacklisted for an hour and a half by the time the bot crashed due to unrelated memory issues. Please try to avoid spreading rumors :)"
Funny how it was working up until I started my bots.
lying to the public just to cover up your broken bot won't help you :>

**Comment by Keterr** [comment]
It wasn't working until you started up your bots, if you've been paying any attention, it's been going down semi regularly in the past weeks due to memory issues. Surprise surprise, the db crashed due to memory issues again. It's cute that you think you had anything to do with it by spamming tul!stats though - a command that incurs pretty much no processing or memory load at all.
